# Configuration for readthedocs.org
# cf https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  image: latest

python:
   version: 3.7
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs

sphinx:
  builder: html
  configuration: docs/conf.py
